use cantabular api extension: GetDimensionsByName
ONSdigital/dp-import-cantabular-dataset pull request #37
Opened 2022-01-14 16:47 UTC by DavidSubiros

### What

- replaced `GetCodebook` with `GetDimensionsByName`, which does a graphQL call against Cantabular API Extension
- added new config paramter for Cantabular API Ext URL
- added healthcheck checker for Cantabular API Ext

### How to review

- Make sure code changes make sense
- Make sure unit/component tests pass
- (info) tested locally with dp-compose and full import/export script

### Who can review

anyone

2022-01-25 12:23 UTC, redhug1 requested changes
Please can you fix these:
service/service.go
lines 71, 100, 209 : Unhandled error

cmd/test-consumer/main.go
lines 105, 108 : Unhandled error

features/steps/component.go
lines 114, 147, 200, 210, 223 : Unhandled error
lines 30, 31, 32 : Type can be omitted

2022-01-26 11:16 UTC, redhug1 approved these changes
LGTM

2022-01-26 21:22 UTC, redhug1 requested changes
I think you meant to update kafka lib to v3.1.1

2022-01-27 11:21 UTC, redhug1 requested changes
kafka update to v3.1.1 in go mod ...

plus other single comment.

2022-01-27 11:21 UTC, redhug1 commented on ci/scripts/component.sh
> +echo "please ignore error codes 0, like so: ERROR[xxxx] 0, as error code 0 means that there was no error"
needs a CR here

2022-01-27 16:52 UTC, DavidSubiros commented
> I think you meant to update kafka lib to v3.1.1

yes, it should be updated in this commit: https://github.com/ONSdigital/dp-import-cantabular-dataset/pull/37/commits/cb49b6403e94080ed83053c1d6e30a9a53e45964

2022-01-28 08:42 UTC, redhug1 requested changes
Those changes look OK, but:

I thought i had already reported these problems with dp-import-cantabular-dataset in github, but i could be wrong, so here they are again, just in case:

component.go line 118 is currently:
	if c.consumer.Start(); err != nil {
which is showing an unhandled error, so i think maybe it should be:
	if err = c.consumer.Start(); err != nil {

A similar error exists in:

 main.go, line 110

Also, line 223 in service.go is an Unhandled error

2022-01-28 13:59 UTC, redhug1 approved these changes
LGTM

2022-01-28 14:29 UTC, merged